<?xml version="1.0"?>

<!--
Copyright (c) 2018 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="platform">
  
  <!-- Platform parameters -->
  <xacro:property name="width" value="0.08"/>

  <xacro:property name="thickness" value="0.04"/>

  <xacro:property name="platform_lift" value="0.075"/>

  <xacro:property name="platform_height" value="0.32"/>

  <xacro:property name="platform_width" value="0.7"/>

  <xacro:property name="platform_length" value="0.98"/>

  <link name="platform_base" />

  <xacro:macro name="beam_support" params="prefix:='' xyz:='0 0 0' rpy:='0 0 0' z=''">
    <link name="beam_support_${prefix}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${z}" />
        </geometry>
        <material name="grey_blue">
          <color rgba="0.3 0.3 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${z}" />
        </geometry>
      </collision>
    </link>
    <!-- <joint name="platform_base_beam_support_${prefix}_joint" type="fixed">
      <parent link="platform_base" />
      <child link = "beam_support_${prefix}" />
      <origin xyz="${xyz}" 
              rpy="${rpy}" />
    </joint> -->
    <!-- Individual link colouring still needed in Gazebo 2.x -->
    <gazebo reference="beam_support_${prefix}"><material>Gazebo/Blue</material></gazebo>
  </xacro:macro>

  <xacro:macro name="beam" params="prefix:='' xyz:='0 0 0' rpy:='0 0 0' x:='0.0' y:='0.0'">
    <link name="beam_${prefix}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${x} ${y} ${thickness}" />
        </geometry>
        <material name="dark_grey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${x} ${y} ${thickness}" />
        </geometry>
      </collision>
    </link>
    <!-- <joint name="platform_base_beam_${prefix}_joint" type="fixed">
      <parent link="platform_base" />
      <child link = "beam_${prefix}" />
      <origin xyz="${xyz}" 
              rpy="${rpy}" />
    </joint> -->
    <!-- Individual link colouring still needed in Gazebo 2.x -->
    <gazebo reference="beam_${prefix}"><material>Gazebo/Grey</material></gazebo>
  </xacro:macro>

  <!-- beam_support_front_right link -->
  <xacro:beam_support prefix="front_right"
                      xyz="${-(platform_width / 2) + (width /2)} 
                           ${-(platform_length / 2) - (width /2)} 
                           ${platform_lift + thickness + (platform_height / 2)}"
                      rpy="0.0 0.0 0.0"
                      z="${platform_height}">
  </xacro:beam_support>

  <!-- beam_support_front_left link -->
  <xacro:beam_support prefix="front_left" 
                      xyz="${(platform_width / 2) - (width /2)} 
                           ${-(platform_length / 2) - (width /2)} 
                           ${platform_lift + thickness + (platform_height / 2)}"
                      rpy="0.0 0.0 0.0"
                      z="${platform_height}">
  </xacro:beam_support>

  <!-- beam_support_back_right link -->
  <xacro:beam_support prefix="back_right"
                      xyz="${-(platform_width / 2) + (width /2)} 
                           ${(platform_length / 2) + (width /2)} 
                           ${platform_lift + thickness + (platform_height / 2)}"
                      rpy="0.0 0.0 0.0"
                      z="${platform_height}">
  </xacro:beam_support>

  <!-- beam_support_back_left link -->
  <xacro:beam_support prefix="back_left"
                      xyz="${(platform_width / 2) - (width /2)} 
                           ${(platform_length / 2) + (width /2)} 
                           ${platform_lift + thickness + (platform_height / 2)}"
                      rpy="0.0 0.0 0.0"
                      z="${platform_height}">
  </xacro:beam_support>

  <!-- beam_support_robot_bottom link -->
  <xacro:beam_support prefix="robot_bottom"
                      xyz="0.0 
                           ${(platform_length / 2) -0.225 - (width /2)} 
                           ${platform_lift + thickness + (platform_height / 2)}"
                      rpy="0.0 0.0 0.0"
                      z="${platform_height}">
  </xacro:beam_support>

  <!-- beam_support_robot_top link -->
  <xacro:beam_support prefix="robot_top"
                      xyz="0.0 
                           ${(platform_length / 2) -0.225 - (width /2)} 
                           ${platform_lift + platform_height + (thickness * 2) + (0.15 / 2)}"
                      rpy="0.0 0.0 0.0"
                      z="0.15">
  </xacro:beam_support>

  <!-- beam_middle_bottom link -->
  <xacro:beam prefix="middle_bottom"
                    xyz="0.0 0.0 ${platform_lift + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${width}"
                    y="${platform_length}">
  </xacro:beam>

  <!-- beam_middle_top link -->
  <xacro:beam prefix="middle_top"
                    xyz="0.0 0.0 ${platform_lift + thickness + platform_height + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${width}"
                    y="${platform_length}">
  </xacro:beam>

  <!-- beam_left_bottom link -->
  <xacro:beam prefix="left_bottom"
                    xyz="${(platform_width / 2) - (width / 2)} 
                         0.0 
                         ${platform_lift + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${width}"
                    y="${platform_length}">
  </xacro:beam>

  <!-- beam_left_top link -->
  <xacro:beam prefix="left_top"
                    xyz="${(platform_width / 2) - (width / 2)} 
                         0.0 
                         ${platform_lift + thickness + platform_height + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${width}"
                    y="${platform_length}">
  </xacro:beam>

  <!-- beam_right_bottom link -->
  <xacro:beam prefix="right_bottom"
                    xyz="${-(platform_width / 2) + (width / 2)} 
                         0.0 
                         ${platform_lift + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${width}"
                    y="${platform_length}">
  </xacro:beam>

  <!-- beam_right_top link -->
  <xacro:beam prefix="right_top"
                    xyz="${-(platform_width / 2) + (width / 2)} 
                         0.0 
                         ${platform_lift + thickness + platform_height + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${width}"
                    y="${platform_length}">
  </xacro:beam>

  <!-- beam_front_bottom link -->
  <xacro:beam prefix="front_bottom"
                    xyz="0.0
                         ${-(platform_length / 2) - (width / 2)} 
                         ${platform_lift + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${platform_width}"
                    y="${width}">
  </xacro:beam>

  <!-- beam_front_top link -->
  <xacro:beam prefix="front_top"
                    xyz="0.0
                         ${-(platform_length / 2) - (width / 2)} 
                         ${platform_lift + thickness + platform_height + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${platform_width}"
                    y="${width}">
  </xacro:beam>

  <!-- beam_back_bottom link -->
  <xacro:beam prefix="back_bottom"
                    xyz="0.0
                         ${(platform_length / 2) + (width / 2)} 
                         ${platform_lift + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${platform_width }"
                    y="${width}">
  </xacro:beam>

  <!-- beam_back_top link -->
  <xacro:beam prefix="back_top"
                    xyz="0.0
                         ${(platform_length / 2) + (width / 2)} 
                         ${platform_lift + thickness + platform_height + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${platform_width}"
                    y="${width}">
  </xacro:beam>

  <!-- beam_connect_left_bottom link -->
  <xacro:beam prefix="connect_left_bottom"
                    xyz="${platform_width / 4 - (width * 1.5) / 2 + (width * 0.5)}
                         0.0
                         ${platform_lift + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${platform_width / 2 - (width * 1.5)}"
                    y="${width}">
  </xacro:beam>

  <!-- beam_connect_left_top link -->
  <xacro:beam prefix="connect_left_top"
                    xyz="${platform_width / 4 - (width * 1.5) / 2 + (width * 0.5)}
                         0.0
                         ${platform_lift + thickness + platform_height + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${platform_width / 2 - (width * 1.5)}"
                    y="${width}">
  </xacro:beam>

  <!-- beam_connect_right_bottom link -->
  <xacro:beam prefix="connect_right_bottom"
                    xyz="${-platform_width / 4 + (width * 1.5) / 2 - (width * 0.5)}
                         0.0
                         ${platform_lift + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${platform_width / 2 - (width * 1.5)}"
                    y="${width}">
  </xacro:beam>

  <!-- beam_connect_right_top link -->
  <xacro:beam prefix="connect_right_top"
                    xyz="${-platform_width / 4 + (width * 1.5) / 2 - (width * 0.5)}
                         0.0
                         ${platform_lift + thickness + platform_height + (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${platform_width / 2 - (width * 1.5)}"
                    y="${width}">
  </xacro:beam>

  <!-- beam_camera_vertical link -->
  <xacro:beam prefix="camera_vertical"
                    xyz="${-(platform_width / 2) + (width / 2)} 
                         ${(platform_length / 2) + (width / 2) + (thickness / 2)} 
                         ${platform_lift + (thickness * 2) + platform_height + (1.0 / 2)}"
                    rpy="${pi / 2} 0.0 0.0"
                    x="${width}"
                    y="1.0">
  </xacro:beam>

  <!-- beam_camera_horizontal link -->
  <xacro:beam prefix="camera_horizontal"
                    xyz="${-(platform_width / 2) + (width / 2)} 
                         ${(platform_length / 2) + (width / 2) - (0.8 / 2)} 
                         ${platform_lift + (thickness * 2) + platform_height + 1.0 - (thickness / 2)}"
                    rpy="0.0 0.0 0.0"
                    x="${width}"
                    y="0.8">
  </xacro:beam>

  <!-- beam_camera_tilt link -->
  <xacro:beam prefix="camera_tilt"
                    xyz="${-(platform_width / 2) + (width / 2)} 
                         0.285 
                         ${platform_lift + (thickness * 2) + platform_height + 0.85 - (thickness / 2)}"
                    rpy="-${pi / 6} 0.0 0.0"
                    x="${width}"
                    y="0.59">
  </xacro:beam>

  <link name="operation_surface">
    <visual>
      <origin xyz="0 0 -0.0125" rpy="0 0 0"/>
      <geometry>
        <box size="0.7 0.6 0.025" />
      </geometry>
      <material name="grey_yellow">
        <color rgba="0.7 0.7 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 -0.0125" rpy="0 0 0"/>
      <geometry>
        <box size="0.7 0.6 0.025" />
      </geometry>
    </collision>
  </link>
  <joint name="platform_base_operation_surface_joint" type="fixed">
    <parent link="platform_base" />
    <child link = "operation_surface" />
    <origin xyz="0.0 
                 ${-(platform_length / 2) - width + (0.6 / 2)} 
                 ${platform_lift + (thickness * 2) + platform_height + 0.025}" 
            rpy="0.0 0.0 0.0" />
  </joint>
  <!-- Individual link colouring still needed in Gazebo 2.x -->
  <gazebo reference="operation_surface"><material>Gazebo/Wood</material></gazebo>

  <link name="robot_install_plate">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${0.15 / 2}" length="0.015"/>
      </geometry>
      <material name="dark_black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${0.15 / 2}" length="0.015"/>
      </geometry>
    </collision>
  </link>
  <joint name="platform_base_robot_install_plate_joint" type="fixed">
    <parent link="beam_support_robot_top" />
    <child link = "robot_install_plate" />
    <origin xyz="0.0 
                 0.0 
                 ${0.015 / 2 + 0.15 / 2}" 
            rpy="0.0 0.0 0.0" />
  </joint>
  <!-- Individual link colouring still needed in Gazebo 2.x -->
  <gazebo reference="robot_install_plate"><material>Gazebo/FlatBlack</material></gazebo>

</robot>